<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/bootstrap.php';
require_once dirname(__DIR__).'/app/operations.php';
$page=$_GET['page']??'home';
if($page==='install'){ require dirname(__DIR__).'/app/install.php'; exit; }
if(!empty($_GET['campaign'])){ $_SESSION['campaign_code']=preg_replace('/[^A-Za-z0-9_-]/','',$_GET['campaign']); }
function layout_start(string $title,string $description='Compare curated Internet and mobility offers, request service and track activation with SecureLink.'): void {
 $u=user();$cssv=(string)(@filemtime(__DIR__.'/assets/app.css')?:'1');$jsv=(string)(@filemtime(__DIR__.'/assets/portal.js')?:'1'); ?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="description" content="<?=e($description)?>"><meta name="theme-color" content="#071022"><meta name="color-scheme" content="dark light"><link rel="stylesheet" href="<?=e(url('assets/app.css?v='.$cssv))?>"><script defer src="<?=e(url('assets/portal.js?v='.$jsv))?>"></script><title><?=e($title)?> · <?=e(envv('APP_NAME','SecureLink'))?></title></head><body><a class="skip-link" href="#main-content">Skip to content</a><div class="ambient ambient-a"></div><div class="ambient ambient-b"></div><div class="signal-line"></div><main class="shell" id="main-content"><nav class="nav glass-nav" aria-label="Primary"><a class="brand" href="<?=e(url('/'))?>"><span class="brand-orbit" aria-hidden="true"><i></i><i></i><b></b></span><span>SECURE<span class="brand-accent">LINK</span></span></a><div class="links"><?php if($u): ?><a href="<?=e(url('?page=deals'))?>">Deals</a><a href="<?=e(url('?page=compare'))?>">Compare</a><a href="<?=e(url('?page=orders'))?>">My Orders</a><?php if(in_array($u['role'],['owner','admin'],true)): ?><a href="<?=e(url('?page=admin'))?>">Admin</a><?php endif; ?><a href="<?=e(url('?page=logout'))?>">Logout</a><?php else: ?><a href="<?=e(url('?page=login'))?>">Sign in</a><a class="nav-cta" href="<?=e(url('?page=register'))?>">Request access</a><?php endif; ?></div></nav><?php if(!empty($_GET['saved'])):?><div class="toast" role="status">Saved successfully.</div><?php endif; ?><?php
}
function layout_end(): void { $u=user(); if($u): ?><nav class="mobile-dock" aria-label="Mobile navigation"><a href="<?=e(url('/'))?>">Home</a><a href="<?=e(url('?page=deals'))?>">Deals</a><a href="<?=e(url('?page=compare'))?>">Compare</a><a href="<?=e(url('?page=orders'))?>">Orders</a></nav><?php endif; echo '</main></body></html>'; }
if($page==='logout'){ session_destroy(); redirect(url('/')); }

if($page==='register'){
 if($_SERVER['REQUEST_METHOD']==='POST'){ rate_limit('register',5,3600); csrf_check(); $n=trim($_POST['name']??'');$em=strtolower(trim($_POST['email']??''));$ph=trim($_POST['phone']??'');$pw=$_POST['password']??''; if(!$n||!filter_var($em,FILTER_VALIDATE_EMAIL)||strlen($pw)<10) exit('Check your details.'); try{$s=db()->prepare("INSERT INTO users(name,email,phone,password_hash) VALUES(?,?,?,?)");$s->execute([$n,$em,$ph,password_hash($pw,PASSWORD_DEFAULT)]);redirect(url('?page=login&registered=1'));}catch(Throwable $e){exit('Account could not be created. Email may already exist.');}}
 layout_start('Request access'); ?><section class="auth-stage"><div class="auth-art"><span class="pill live-pill">PRIVATE ACCESS</span><h1>Join the<br><em>network.</em></h1><p>One account for private offers, guided ordering and activation tracking.</p><div class="auth-signal"><i></i><i></i><i></i><b></b></div></div><div class="card narrow auth-card"><span class="eyebrow">CREATE ACCOUNT / 01</span><h1>Request access</h1><p class="muted">Create your private account. Deals become visible after approval.</p><form method="post"><input type="hidden" name="_token" value="<?=e(csrf())?>"><label>Full name<input name="name" required></label><label>Email<input type="email" name="email" required></label><label>Phone<input name="phone" required></label><label>Password<input type="password" name="password" minlength="10" required></label><button>Create account <span>↗</span></button></form></div></section><?php layout_end();exit;
}
if($page==='login'){
 if($_SERVER['REQUEST_METHOD']==='POST'){rate_limit('login',8,600);csrf_check();$s=db()->prepare('SELECT * FROM users WHERE email=?');$s->execute([strtolower(trim($_POST['email']??''))]);$u=$s->fetch();if($u&&password_verify($_POST['password']??'',$u['password_hash'])){session_regenerate_id(true);$_SESSION['uid']=$u['id'];rate_limit_clear('login');audit((int)$u['id'],'login');redirect(url($u['role']==='customer'?'?page=deals':'?page=admin'));} $err='Invalid email or password.';}
 layout_start('Sign in');?><section class="auth-stage"><div class="auth-art"><span class="pill live-pill">SECURELINK / MEMBER</span><h1>Back to your<br><em>connection.</em></h1><p>Your private offers, requests and activation journey are waiting.</p><div class="auth-signal"><i></i><i></i><i></i><b></b></div></div><div class="card narrow auth-card"><span class="eyebrow">MEMBER ACCESS / 02</span><h1>Welcome back</h1><?php if(!empty($_GET['registered'])):?><p class="alert success">Account created. An administrator must approve access.</p><?php endif;if(isset($err)):?><p class="alert"><?=e($err)?></p><?php endif;?><form method="post"><input type="hidden" name="_token" value="<?=e(csrf())?>"><label>Email<input type="email" name="email" required></label><label>Password<input type="password" name="password" required></label><button>Enter portal <span>↗</span></button></form></div></section><?php layout_end();exit;
}
if($page==='pending'){ $u=require_login(); layout_start('Pending approval');?><section class="card narrow"><span class="pill">PENDING APPROVAL</span><h1>We're reviewing your access.</h1><p class="muted">Your account must be approved before private pricing and offers become available.</p></section><?php layout_end();exit; }

if($page==='deals'){
 $u=require_approved();$category=strtolower(trim($_GET['category']??''));$deals=active_deals($category);
 $cats=[''=>'All','internet'=>'Internet','mobility'=>'Mobility','tv'=>'TV','security'=>'Security','streaming'=>'Streaming','devices'=>'Devices'];
 layout_start('Deals','Browse current approved SecureLink Internet, mobility, TV, security and device offers.');?><div class="hero portal-hero"><div class="hero-copy"><span class="pill live-pill">● PRIVATE NETWORK / APPROVED</span><h1>Find your<br><em>best connection.</em></h1><p class="muted">Clear pricing, credits and terms — then compare providers side by side before you request anything.</p><div class="hero-chips"><span>FIBRE</span><span>5G+</span><span>COMPARE</span></div></div><div class="signal-sculpture" aria-hidden="true"><div class="orb-core"></div><div class="orbit o1"></div><div class="orbit o2"></div><div class="orbit o3"></div><span class="node n1"></span><span class="node n2"></span><span class="node n3"></span></div></div>
 <div class="deal-toolbar"><div><span class="eyebrow">LIVE OFFERS</span><h2>Choose your connection</h2></div><span class="deal-count"><?=count($deals)?> AVAILABLE</span></div>
 <div class="catalog-tabs" role="navigation" aria-label="Deal categories"><?php foreach($cats as $key=>$label):?><a class="<?=$category===$key?'active':''?>" href="<?=e(url('?page=deals'.($key!==''?'&category='.urlencode($key):'')))?>"><?=e($label)?></a><?php endforeach;?></div>
 <div class="grid deal-grid"><?php foreach($deals as $d):$rw=deal_rewards($d);$effective=deal_effective_monthly($d);$providerClass='provider-'.provider_slug($d['provider']);?><article class="card deal-card <?=e($providerClass)?>" data-provider="<?=e(strtolower($d['provider']))?>"><div class="card-glow"></div><div class="deal-card-head"><span class="pill"><?=e($d['provider'])?> · <?=e($d['category'])?></span><?php if(!empty($d['featured'])):?><span class="featured-badge">FEATURED</span><?php endif;?></div><h2><?=e($d['name'])?></h2><p class="muted"><?=e($d['description'])?></p><div class="deal-price-row"><?php if((float)($d['regular_price']??0)>(float)$d['monthly_price']):?><span class="regular-price">$<?=number_format((float)$d['regular_price'],2)?></span><?php endif;?><div class="price">$<?=number_format((float)$d['monthly_price'],2)?><small>/mo</small></div></div><div class="deal-facts"><?php if(!empty($d['speed_data'])):?><span><small>Speed / data</small><b><?=e($d['speed_data'])?></b></span><?php endif;?><span><small>Term</small><b><?=!empty($d['term_months'])?(int)$d['term_months'].' mo':'Month-to-month'?></b></span><?php if($rw>0):?><span><small>Listed rewards</small><b>$<?=number_format($rw,0)?></b></span><span><small>Effective</small><b>$<?=number_format($effective,2)?>/mo*</b></span><?php endif;?></div><?php if($rw>0):?><div class="reward"><strong>$<?=number_format($rw,0)?> potential rewards</strong><br><small>*Effective monthly spreads listed one-time rewards over <?=deal_term($d)?> months.</small></div><?php endif;?><?php if(!empty($d['expires_at'])):?><p class="expiry">Offer expiry: <?=e(date('M j, Y',strtotime($d['expires_at'])))?></p><?php endif;?><div class="deal-actions"><a class="button" href="<?=e(url('?page=apply&id='.$d['id']))?>">Get this offer <span>↗</span></a><a class="button secondary compare-button" href="<?=e(url('?page=compare&left='.$d['id']))?>">Compare</a></div><?php if(!empty($d['fine_print'])):?><details class="terms"><summary>Important terms</summary><p><?=e($d['fine_print'])?></p></details><?php endif;?></article><?php endforeach;if(!$deals):?><section class="card empty-state"><div class="empty-icon">⌁</div><h2>No active deals</h2><p class="muted">There are no live offers in this category right now.</p><a class="button secondary" href="<?=e(url('?page=deals'))?>">View all offers</a></section><?php endif;?></div><?php layout_end();exit;
}
if($page==='compare'){
 $u=require_approved();$deals=active_deals();$byId=[];foreach($deals as $x)$byId[(int)$x['id']]=$x;
 $leftId=(int)($_GET['left']??0);$rightId=(int)($_GET['right']??0);
 if(!$leftId&&count($deals)>0){foreach($deals as $x){if(strtolower($x['provider'])==='telus'){$leftId=(int)$x['id'];break;}}if(!$leftId)$leftId=(int)$deals[0]['id'];}
 if(!$rightId&&$leftId){$leftCandidate=$byId[$leftId]??null;foreach($deals as $x){if((int)$x['id']!==$leftId && (!$leftCandidate || (strtolower($x['provider'])!==strtolower($leftCandidate['provider']) && strtolower($x['category'])===strtolower($leftCandidate['category'])))){$rightId=(int)$x['id'];break;}}}
 $left=$byId[$leftId]??null;$right=$byId[$rightId]??null;
 layout_start('Compare offers','Compare SecureLink offers side by side by monthly price, term, rewards and effective cost.');?><section class="compare-hero"><span class="eyebrow">SIDE-BY-SIDE</span><h1>Compare before<br><em>you commit.</em></h1><p class="muted">Pick any two live offers. SecureLink calculates listed rewards and effective monthly cost without hiding the terms.</p></section>
 <form class="compare-picker card" method="get"><input type="hidden" name="page" value="compare"><label>Offer A<select name="left"><?php foreach($deals as $x):?><option value="<?=$x['id']?>" <?=$leftId===(int)$x['id']?'selected':''?>><?=e($x['provider'].' · '.$x['name'].' · $'.number_format((float)$x['monthly_price'],2).'/mo')?></option><?php endforeach;?></select></label><span class="compare-vs">VS</span><label>Offer B<select name="right"><?php foreach($deals as $x):?><option value="<?=$x['id']?>" <?=$rightId===(int)$x['id']?'selected':''?>><?=e($x['provider'].' · '.$x['name'].' · $'.number_format((float)$x['monthly_price'],2).'/mo')?></option><?php endforeach;?></select></label><button>Compare offers</button></form>
 <?php if($left&&$right):$le=deal_effective_monthly($left);$re=deal_effective_monthly($right);$leftBest=$le<$re;$rightBest=$re<$le;?><div class="compare-grid"><article class="compare-offer provider-<?=e(provider_slug($left['provider']))?>"><?php if($leftBest):?><span class="best-value">BEST VALUE*</span><?php endif;?><span class="pill"><?=e($left['provider'])?></span><h2><?=e($left['name'])?></h2><div class="price">$<?=number_format((float)$left['monthly_price'],2)?><small>/mo</small></div><p><?=e($left['description'])?></p><a class="button" href="<?=e(url('?page=apply&id='.$left['id']))?>">Choose <?=e($left['provider'])?></a></article><article class="compare-offer provider-<?=e(provider_slug($right['provider']))?>"><?php if($rightBest):?><span class="best-value">BEST VALUE*</span><?php endif;?><span class="pill"><?=e($right['provider'])?></span><h2><?=e($right['name'])?></h2><div class="price">$<?=number_format((float)$right['monthly_price'],2)?><small>/mo</small></div><p><?=e($right['description'])?></p><a class="button" href="<?=e(url('?page=apply&id='.$right['id']))?>">Choose <?=e($right['provider'])?></a></article></div>
 <div class="comparison-table-wrap card"><table class="comparison-table"><thead><tr><th>What matters</th><th><?=e($left['provider'])?></th><th><?=e($right['provider'])?></th></tr></thead><tbody><tr><td>Monthly price</td><td>$<?=number_format((float)$left['monthly_price'],2)?></td><td>$<?=number_format((float)$right['monthly_price'],2)?></td></tr><tr><td>Regular price</td><td><?=!empty($left['regular_price'])?'$'.number_format((float)$left['regular_price'],2):'—'?></td><td><?=!empty($right['regular_price'])?'$'.number_format((float)$right['regular_price'],2):'—'?></td></tr><tr><td>Speed / data</td><td><?=e($left['speed_data']?:'—')?></td><td><?=e($right['speed_data']?:'—')?></td></tr><tr><td>Term</td><td><?=!empty($left['term_months'])?(int)$left['term_months'].' months':'Month-to-month'?></td><td><?=!empty($right['term_months'])?(int)$right['term_months'].' months':'Month-to-month'?></td></tr><tr><td>Listed rewards</td><td>$<?=number_format(deal_rewards($left),0)?></td><td>$<?=number_format(deal_rewards($right),0)?></td></tr><tr><td>Effective monthly*</td><td><strong>$<?=number_format($le,2)?></strong></td><td><strong>$<?=number_format($re,2)?></strong></td></tr><tr><td>Estimated term cost*</td><td>$<?=number_format(deal_term_cost($left),2)?></td><td>$<?=number_format(deal_term_cost($right),2)?></td></tr><tr><td>Expiry</td><td><?=!empty($left['expires_at'])?e(date('M j, Y',strtotime($left['expires_at']))):'Not listed'?></td><td><?=!empty($right['expires_at'])?e(date('M j, Y',strtotime($right['expires_at']))):'Not listed'?></td></tr></tbody></table><p class="compare-note">*Best value/effective cost is a mathematical comparison of listed price and one-time rewards over the plan term. Coverage, taxes, eligibility, installation, device financing and provider-specific conditions can change the right choice.</p></div><?php else:?><section class="card empty-state"><h2>Select two offers</h2><p class="muted">Choose two active offers above to see a complete comparison.</p></section><?php endif;?><?php layout_end();exit;
}
if($page==='apply'){
 $u=require_approved();$id=(int)($_GET['id']??0);$s=db()->prepare("SELECT d.*,p.name provider,p.id provider_id FROM deals d JOIN providers p ON p.id=d.provider_id WHERE d.id=? AND d.status='active' AND p.status='active'");$s->execute([$id]);$d=$s->fetch();if(!$d){http_response_code(404);layout_start('Offer unavailable');?><section class="card narrow empty-state"><h1>Offer unavailable</h1><p class="muted">This offer is no longer active.</p><a class="button" href="<?=e(url('?page=deals'))?>">Back to deals</a></section><?php layout_end();exit;}
 if($_SERVER['REQUEST_METHOD']==='POST'){rate_limit('order_submit',8,3600);csrf_check();$public='SL-'.date('ymd').'-'.strtoupper(bin2hex(random_bytes(3)));$source=(int)($_POST['source_id']??0)?:null;$port=!empty($_POST['porting'])?1:0;$snapshot=json_encode($d,JSON_UNESCAPED_SLASHES);$sql="INSERT INTO orders(public_id,user_id,deal_id,provider_id,category,deal_snapshot,source_id,referred_by,contact_email,contact_phone,service_address,basement_details,porting,current_phone,current_provider,current_account_number,imei,eid,id_type,id_value_encrypted) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";$st=db()->prepare($sql);$st->execute([$public,$u['id'],$d['id'],$d['provider_id'],$d['category'],$snapshot,$source,trim($_POST['referred_by']??''),trim($_POST['email']??$u['email']),trim($_POST['phone']??$u['phone']),trim($_POST['address']??''),trim($_POST['basement']??''),$port,trim($_POST['current_phone']??''),trim($_POST['current_provider']??''),trim($_POST['account_number']??''),trim($_POST['imei']??''),trim($_POST['eid']??''),trim($_POST['id_type']??''),encrypt_secret(trim($_POST['id_value']??''))]);$oid=(int)db()->lastInsertId();if(trim($_POST['referred_by']??'')!==''){$r=db()->prepare("INSERT INTO referrals(order_id,referred_by,referred_customer,reward_amount) VALUES(?,?,?,?)");$r->execute([$oid,trim($_POST['referred_by']),$u['name'],(float)$d['referral_reward']]);}audit((int)$u['id'],'submit_order','order',$oid,['public_id'=>$public]);redirect(url('?page=success&order='.urlencode($public)));}
 $sources=db()->query("SELECT * FROM sale_sources WHERE active=1 ORDER BY name")->fetchAll();$needsAddress=in_array(strtolower($d['category']),['internet','tv','security'],true);layout_start('Apply','Submit a secure service request for the selected SecureLink offer.');?><section class="application-shell"><aside class="application-summary provider-<?=e(provider_slug($d['provider']))?>"><span class="pill"><?=e($d['provider'])?> · <?=e($d['category'])?></span><h1><?=e($d['name'])?></h1><div class="price">$<?=number_format((float)$d['monthly_price'],2)?><small>/mo</small></div><?php if(!empty($d['speed_data'])):?><p><strong><?=e($d['speed_data'])?></strong></p><?php endif;?><p class="muted"><?=e($d['description'])?></p><div class="summary-facts"><span>Term <b><?=!empty($d['term_months'])?(int)$d['term_months'].' months':'Month-to-month'?></b></span><span>Rewards <b>$<?=number_format(deal_rewards($d),0)?></b></span></div></aside>
 <section class="card application-card"><div class="stepper" aria-label="Application progress"><button type="button" class="step-dot active" data-step-target="1"><b>1</b><span>Plan</span></button><button type="button" class="step-dot" data-step-target="2"><b>2</b><span>Contact</span></button><button type="button" class="step-dot" data-step-target="3"><b>3</b><span>Details</span></button><button type="button" class="step-dot" data-step-target="4"><b>4</b><span>Review</span></button></div>
 <form method="post" class="multi-step-form" data-storage-key="securelink-apply-<?=$d['id']?>"><input type="hidden" name="_token" value="<?=e(csrf())?>">
 <div class="form-step active" data-step="1"><span class="eyebrow">STEP 1 OF 4</span><h2>Confirm your offer</h2><div class="review-plan"><b><?=e($d['provider'])?> · <?=e($d['name'])?></b><span>$<?=number_format((float)$d['monthly_price'],2)?>/month</span></div><label>How did you hear about this offer?<select name="source_id" data-persist><option value="">Select</option><?php foreach($sources as $x):?><option value="<?=$x['id']?>"><?=e($x['name'])?></option><?php endforeach;?></select></label><label>Referred by (optional)<input name="referred_by" data-persist></label><div class="step-actions"><button type="button" class="next-step">Continue <span>→</span></button></div></div>
 <div class="form-step" data-step="2"><span class="eyebrow">STEP 2 OF 4</span><h2>Your contact details</h2><div class="formgrid"><label>Email<input type="email" name="email" value="<?=e($u['email'])?>" required data-persist></label><label>Phone<input name="phone" value="<?=e($u['phone'])?>" required data-persist></label></div><p class="form-help">We use these details only to review this request and coordinate activation.</p><div class="step-actions"><button type="button" class="secondary prev-step">Back</button><button type="button" class="next-step">Continue <span>→</span></button></div></div>
 <div class="form-step" data-step="3"><span class="eyebrow">STEP 3 OF 4</span><h2>Service details</h2><?php if(strtolower($d['category'])==='mobility'):?><label>Identity option<select name="id_type" required><option value="">Select</option><option>Driver's Licence</option><option>Provider-approved alternative</option></select></label><label>Identity value<input name="id_value" autocomplete="off" required data-sensitive="true"></label><label class="check-row"><input type="checkbox" name="porting" value="1" data-persist> I am porting my current number</label><div class="formgrid porting-fields"><label>Current phone number<input name="current_phone"></label><label>Current provider<input name="current_provider"></label><label>Current provider account number<input name="account_number" data-sensitive="true"></label></div><h3>eSIM details (if applicable)</h3><div class="formgrid"><label>IMEI<input name="imei" data-sensitive="true"></label><label>EID<input name="eid" data-sensitive="true"></label></div><?php else:?><label>Service address<input name="address" <?=$needsAddress?'required':''?> placeholder="Street, unit, city, province, postal code" data-persist></label><label>Suite / access notes<textarea name="basement" data-persist placeholder="Unit, basement, buzzer or entrance details."></textarea></label><label>Accepted ID type<select name="id_type" required><option value="">Select</option><option>Driver's Licence</option><option>Provincial ID</option><option>Other provider-approved ID</option></select></label><label>ID value<input name="id_value" autocomplete="off" required data-sensitive="true"></label><?php endif;?><p class="privacy-note">Sensitive identity fields are never saved in browser progress storage.</p><div class="step-actions"><button type="button" class="secondary prev-step">Back</button><button type="button" class="next-step">Review request <span>→</span></button></div></div>
 <div class="form-step" data-step="4"><span class="eyebrow">STEP 4 OF 4</span><h2>Review & submit</h2><div class="review-summary" aria-live="polite"></div><div class="alert">Submitting creates a request for manual processing. Provider eligibility, final pricing, taxes, installation and appointment availability remain subject to confirmation.</div><div class="step-actions"><button type="button" class="secondary prev-step">Back</button><button type="submit">Submit order request <span>↗</span></button></div></div>
 </form></section></section><?php layout_end();exit;
}
if($page==='success'){require_login();layout_start('Submitted');?><section class="card narrow success-card" data-clear-application-storage="true"><span class="pill">REQUEST RECEIVED</span><h1>You're all set.</h1><p>Order request <strong><?=e($_GET['order']??'')?></strong> has been submitted.</p><div class="alert success"><strong>We'll contact you within 1 hour during business hours</strong> to review your request, process the order and confirm your appointment date and time.</div><a class="button" href="<?=e(url('?page=orders'))?>">Track my request</a></section><?php layout_end();exit;}
if($page==='orders'){ $u=require_login();$s=db()->prepare("SELECT o.*,d.name deal,p.name provider FROM orders o JOIN deals d ON d.id=o.deal_id JOIN providers p ON p.id=o.provider_id WHERE o.user_id=? ORDER BY o.id DESC");$s->execute([$u['id']]);layout_start('My orders');?><h1>My orders</h1><div class="grid"><?php foreach($s as $o):?><article class="card"><span class="pill"><?=e(strtoupper($o['status']))?></span><h2><?=e($o['provider'])?> · <?=e($o['deal'])?></h2><p><strong><?=e($o['public_id'])?></strong></p><?php if($o['appointment_at']):?><p>Appointment: <?=e($o['appointment_at'])?></p><?php endif;?><p class="muted">Submitted <?=e($o['created_at'])?></p></article><?php endforeach;?></div><?php layout_end();exit;}

if($page==='admin'){ require dirname(__DIR__).'/app/admin.php'; exit; }
if($page==='export'){ $a=require_admin();$type=$_GET['type']??'';$maps=['leads'=>"SELECT id,name,email,phone,stage,sales_agent,next_follow_up_at,lost_reason,created_at FROM leads",'orders'=>"SELECT public_id,category,status,contact_email,contact_phone,referred_by,sales_agent,provider_reference,appointment_at,lost_reason,created_at FROM orders",'referrals'=>"SELECT referred_by,referred_customer,reward_amount,status,eligible_at,paid_at,payment_reference,created_at FROM referrals"];
 if(!isset($maps[$type])){http_response_code(400);exit('Invalid export');}$rows=db()->query($maps[$type])->fetchAll();header('Content-Type: text/csv');header('Content-Disposition: attachment; filename="'.$type.'-'.date('Y-m-d').'.csv"');$out=fopen('php://output','w');if($rows){fputcsv($out,array_keys($rows[0]));foreach($rows as $r)fputcsv($out,$r);}fclose($out);exit;}
if($page==='home'){
 $homeUser=user();$approved=$homeUser && ($homeUser['role']!=='customer'||$homeUser['status']==='approved');$primary=$approved?url('?page=deals'):url('?page=register');$compare=$approved?url('?page=compare'):url('?page=register');$featured=$approved?featured_deals(3):[];
 layout_start('Private telecom offers','A premium private telecom portal for comparing Internet and mobility offers, requesting service and tracking activation.');?><section class="storefront-hero"><div class="storefront-copy"><span class="eyebrow">SECURELINK / PRIVATE TELECOM</span><h1>Find the right<br><em>connection.</em></h1><p>Compare curated Internet and mobility offers, understand the real cost and hand the activation work to a human.</p><div class="hero-actions"><a class="button" href="<?=e($primary)?>"><?=$approved?'Browse live deals':'Request private access'?> <span>↗</span></a><a class="button secondary" href="<?=e($compare)?>">Compare providers</a></div><div class="trust-row"><span>Clear pricing</span><span>Side-by-side comparison</span><span>Human processing</span></div></div><div class="provider-stage" aria-hidden="true"><div class="provider-panel telus-panel"><small>TELUS</small><b>PureFibre<br>+ Mobility</b><i></i></div><div class="provider-panel rogers-panel"><small>ROGERS</small><b>Internet<br>+ 5G</b><i></i></div></div></section>
 <section class="shop-by"><div class="section-heading"><span class="eyebrow">SHOP YOUR WAY</span><h2>Start with what you need.</h2></div><div class="shop-grid"><a href="<?=e($approved?url('?page=deals&category=internet'):url('?page=register'))?>" class="shop-card"><span>01</span><div class="shop-icon">⌁</div><h3>Internet</h3><p>Fibre, cable and wireless home Internet offers.</p><b>Explore →</b></a><a href="<?=e($approved?url('?page=deals&category=mobility'):url('?page=register'))?>" class="shop-card"><span>02</span><div class="shop-icon">◔</div><h3>Mobility</h3><p>Data, roaming and BYOD plans without the clutter.</p><b>Explore →</b></a><a href="<?=e($approved?url('?page=deals&category=tv'):url('?page=register'))?>" class="shop-card"><span>03</span><div class="shop-icon">▣</div><h3>Bundles</h3><p>Build around Internet, TV and connected-home services.</p><b>Explore →</b></a><a href="<?=e($compare)?>" class="shop-card compare-shop"><span>04</span><div class="shop-icon">⇄</div><h3>Compare</h3><p>Put two offers side by side and see effective cost.</p><b>Compare →</b></a></div></section>
 <section class="provider-split"><article class="provider-story telus-story"><span>TELUS INSPIRED EXPERIENCE</span><h2>Clean. Calm.<br>Fibre focused.</h2><p>When you open a TELUS offer, its purple and green visual language makes the provider instantly recognizable while SecureLink remains the platform.</p></article><article class="provider-story rogers-story"><span>ROGERS INSPIRED EXPERIENCE</span><h2>Bold. Direct.<br>Offer focused.</h2><p>Rogers offers use a sharper red-led treatment so comparing providers feels natural instead of mixing both identities into one card.</p></article></section>
 <?php if($featured):?><section class="featured-section"><div class="section-heading"><span class="eyebrow">FEATURED NOW</span><h2>Worth a closer look.</h2></div><div class="grid deal-grid"><?php foreach($featured as $d):?><article class="card home-deal provider-<?=e(provider_slug($d['provider']))?>"><span class="pill"><?=e($d['provider'].' · '.$d['category'])?></span><h3><?=e($d['name'])?></h3><div class="price">$<?=number_format((float)$d['monthly_price'],2)?><small>/mo</small></div><p><?=e($d['speed_data']?:$d['description'])?></p><div class="deal-actions"><a class="button" href="<?=e(url('?page=apply&id='.$d['id']))?>">Get offer</a><a class="button secondary" href="<?=e(url('?page=compare&left='.$d['id']))?>">Compare</a></div></article><?php endforeach;?></div></section><?php endif;?>
 <section class="how-it-works"><div><span class="eyebrow">HOW IT WORKS</span><h2>Three steps.<br>No telecom maze.</h2></div><ol><li><b>01</b><span><strong>Discover</strong>Browse approved offers with the important terms upfront.</span></li><li><b>02</b><span><strong>Compare</strong>See monthly price, rewards, term and effective cost side by side.</span></li><li><b>03</b><span><strong>Activate</strong>Submit once and a human reviews, processes and confirms the order.</span></li></ol></section>
 <section class="portal-cta"><span class="eyebrow">SECURELINK / 2026</span><h2>Choose with clarity.<br>Activate with confidence.</h2><a class="button" href="<?=e($primary)?>"><?=$approved?'View live offers':'Request private access'?> ↗</a></section><?php layout_end();exit;
}
http_response_code(404);layout_start('Page not found');?><section class="card narrow empty-state error-page"><div class="error-code">404</div><h1>That page is off-network.</h1><p class="muted">The link may be outdated or the page may have moved.</p><a class="button" href="<?=e(url('/'))?>">Return home</a></section><?php layout_end();
