<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/bootstrap.php';
require_once dirname(__DIR__).'/app/operations.php';
require_once dirname(__DIR__).'/app/production.php';
run_maintenance();
$page=$_GET['page']??'home';
if($page==='install'){ require dirname(__DIR__).'/app/install.php'; exit; }
if(!empty($_GET['campaign'])){ $_SESSION['campaign_code']=preg_replace('/[^A-Za-z0-9_-]/','',$_GET['campaign']); }
function layout_start(string $title): void { $u=user(); ?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><?php $cssv=(string)(@filemtime(__DIR__.'/assets/app.css')?:time());$jsv=(string)(@filemtime(__DIR__.'/assets/portal.js')?:time());?><link rel="stylesheet" href="<?=e(url('assets/app.css?v='.$cssv))?>"><script defer src="<?=e(url('assets/portal.js?v='.$jsv))?>"></script><title><?=e($title)?> · <?=e(envv('APP_NAME','Telecom Portal'))?></title></head><body class="cinematic"><div class="cosmos"></div><div class="network-grid"></div><main class="shell"><nav class="nav portal-nav"><a class="brand sl-brand" href="<?=e(url('/'))?>"><i class="sl-logo"></i><span>SECURELINK<small>PRIVATE TELECOM NETWORK</small></span></a><div class="links"><?php if($u): ?><a href="<?=e(url('?page=deals'))?>">Deals</a><a href="<?=e(url('?page=orders'))?>">My Orders</a><?php if(in_array($u['role'],['owner','admin'],true)): ?><a href="<?=e(url('?page=admin'))?>">Admin</a><?php endif; ?><a href="<?=e(url('?page=logout'))?>">Logout</a><?php else: ?><a href="<?=e(url('?page=login'))?>">Sign in</a><a href="<?=e(url('?page=register'))?>">Request access</a><?php endif; ?></div></nav><?php }
function layout_end(): void { echo '</main></body></html>'; }
if($page==='logout'){ session_destroy(); redirect(url('/')); }

if($page==='register'){
 if($_SERVER['REQUEST_METHOD']==='POST'){ csrf_check(); $n=trim($_POST['name']??'');$em=strtolower(trim($_POST['email']??''));$ph=trim($_POST['phone']??'');$pw=$_POST['password']??''; if(!$n||!filter_var($em,FILTER_VALIDATE_EMAIL)||strlen($pw)<10) exit('Check your details.'); try{$s=db()->prepare("INSERT INTO users(name,email,phone,password_hash) VALUES(?,?,?,?)");$s->execute([$n,$em,$ph,password_hash($pw,PASSWORD_DEFAULT)]);redirect(url('?page=login&registered=1'));}catch(Throwable $e){exit('Account could not be created. Email may already exist.');}}
 layout_start('Request access'); ?><section class="auth-stage"><div class="auth-story"><span class="login-kicker">PRIVATE • APPROVAL GATED</span><h1>Join the<br><em>network.</em></h1><p>Create one SecureLink account for private offers, guided ordering and activation tracking.</p><div class="auth-orbit"><i></i><i></i><i></i><b></b></div></div><div class="card narrow login-glass"><div class="login-mark"><i class="sl-logo"></i><b>SECURELINK</b><small>REQUEST ACCESS</small></div><h2>Create your account</h2><p class="muted">Your account stays pending until an administrator approves it.</p><form method="post"><input type="hidden" name="_token" value="<?=e(csrf())?>"><label>Full name<input name="name" required></label><label>Email<input type="email" name="email" required></label><label>Phone<input name="phone" required></label><label>Password<input type="password" name="password" minlength="10" required></label><button>Create account <span>→</span></button></form><a class="new-access" href="<?=e(url('?page=login'))?>"><span><b>Already approved?</b><small>Sign in to your private portal.</small></span><b>→</b></a></div></section><?php layout_end();exit;
}
if($page==='login'){
 if($_SERVER['REQUEST_METHOD']==='POST'){csrf_check();$s=db()->prepare('SELECT * FROM users WHERE email=?');$s->execute([strtolower(trim($_POST['email']??''))]);$u=$s->fetch();if($u&&password_verify($_POST['password']??'',$u['password_hash'])){session_regenerate_id(true);$_SESSION['uid']=$u['id'];audit((int)$u['id'],'login');redirect(url($u['role']==='customer'?'?page=deals':'?page=admin'));} $err='Invalid email or password.';}
 layout_start('Sign in');?><section class="login-stage"><div class="login-story"><span class="login-kicker">FAST • RELIABLE • SIMPLE</span><h1>Welcome to<br><em>SecureLink.</em></h1><p>Your private portal for exclusive Internet, Mobility and Device offers with personal support.</p><div class="wifi-art" aria-hidden="true"><i></i><i></i><i></i><b></b></div><div class="login-benefits"><div><b>⌁</b><span><strong>Internet</strong><small>Fibre speeds for every home</small></span></div><div><b>◔</b><span><strong>Mobility</strong><small>Plans that actually fit you</small></span></div><div><b>▣</b><span><strong>Devices</strong><small>Latest phones and accessories</small></span></div><div><b>☆</b><span><strong>Exclusive deals</strong><small>For approved customers</small></span></div></div></div><div class="card narrow login-glass"><div class="login-mark"><i class="sl-logo"></i><b>SECURELINK</b><small>PRIVATE PORTAL</small></div><h2>Sign in to your account</h2><p class="muted">Access your offers, orders and activation status in one place.</p><?php if(!empty($_GET['registered'])):?><p class="alert success">Account created. An administrator must approve access.</p><?php endif;if(isset($err)):?><p class="alert"><?=e($err)?></p><?php endif;?><form method="post"><input type="hidden" name="_token" value="<?=e(csrf())?>"><label>Email address<input type="email" name="email" placeholder="you@example.com" required></label><label>Password<input type="password" name="password" placeholder="Enter your password" required></label><button>Sign in <span>→</span></button></form><a class="new-access" href="<?=e(url('?page=register'))?>"><span><b>New to SecureLink?</b><small>Request access to view exclusive offers.</small></span><b>→</b></a></div></section><?php layout_end();exit;
}
if($page==='pending'){ $u=require_login(); layout_start('Pending approval');?><section class="card narrow"><span class="pill">PENDING APPROVAL</span><h1>We're reviewing your access.</h1><p class="muted">Your account must be approved before private pricing and offers become available.</p></section><?php layout_end();exit; }

if($page==='deals'){
 $u=require_approved(); $q=db()->query("SELECT d.*,p.name provider FROM deals d JOIN providers p ON p.id=d.provider_id WHERE d.status='active' AND p.status='active' AND (d.starts_at IS NULL OR d.starts_at<=datetime('now')) AND (d.expires_at IS NULL OR d.expires_at>=datetime('now')) ORDER BY p.display_order,d.id DESC"); $deals=$q->fetchAll();
 layout_start('Deals');?><section class="portal-dashboard"><div><span class="login-kicker">SECURELINK • LIVE CATALOGUE</span><h1>Choose your<br><em>connection.</em></h1><p class="muted">Curated private offers available to your approved account.</p></div><div class="catalog-orbit"><i></i><i></i><b></b></div></section><div class="catalog-tools"><span><?=count($deals)?> ACTIVE OFFERS</span><div class="catalog-filters"><button type="button" data-filter="all" class="active">All</button><button type="button" data-filter="internet">Internet</button><button type="button" data-filter="mobility">Mobility</button><button type="button" data-filter="devices">Devices</button><button type="button" data-filter="tv">TV</button><button type="button" data-filter="security">Security</button></div></div><div class="grid deal-grid"><?php foreach($deals as $d):?><article class="card deal-card" data-category="<?=e(strtolower($d['category']))?>"><div class="deal-shine"></div><div class="deal-top"><span class="pill"><?=e($d['provider'])?> · <?=e($d['category'])?></span><span class="deal-dot">● LIVE</span></div><h2><?=e($d['name'])?></h2><p class="muted"><?=e($d['description'])?></p><div class="price">$<?=number_format((float)$d['monthly_price'],2)?><small>/mo</small></div><p><?=e($d['speed_data'])?></p><?php $rw=(float)$d['bill_credit']+(float)$d['referral_reward']+(float)$d['other_reward'];if($rw>0):?><div class="reward"><strong>$<?=number_format($rw,0)?> potential rewards</strong><br><small>See terms and eligibility.</small></div><?php endif;?><a class="button deal-cta" href="<?=e(url('?page=apply&id='.$d['id']))?>">Get this deal <span>↗</span></a></article><?php endforeach;if(!$deals):?><section class="card"><h2>No active deals</h2><p class="muted">New offers will appear here when published.</p></section><?php endif;?></div><?php layout_end();exit;
}
if($page==='apply'){
 $u=require_approved();$id=(int)($_GET['id']??0);$s=db()->prepare("SELECT d.*,p.name provider,p.id provider_id FROM deals d JOIN providers p ON p.id=d.provider_id WHERE d.id=? AND d.status='active' AND p.status='active'");$s->execute([$id]);$d=$s->fetch();if(!$d){http_response_code(404);exit('Deal unavailable.');}
 if($_SERVER['REQUEST_METHOD']==='POST'){csrf_check();$public='SL-'.date('ymd').'-'.strtoupper(bin2hex(random_bytes(3)));$source=(int)($_POST['source_id']??0)?:null;$campaign=active_campaign_id();$port=!empty($_POST['porting'])?1:0;$snapshot=json_encode($d,JSON_UNESCAPED_SLASHES);$sql="INSERT INTO orders(public_id,user_id,deal_id,provider_id,category,deal_snapshot,source_id,campaign_id,referred_by,contact_email,contact_phone,service_address,basement_details,porting,current_phone,current_provider,current_account_number,imei,eid,id_type,id_value_encrypted) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";$st=db()->prepare($sql);$st->execute([$public,$u['id'],$d['id'],$d['provider_id'],$d['category'],$snapshot,$source,$campaign,trim($_POST['referred_by']??''),trim($_POST['email']??$u['email']),trim($_POST['phone']??$u['phone']),trim($_POST['address']??''),trim($_POST['basement']??''),$port,trim($_POST['current_phone']??''),trim($_POST['current_provider']??''),trim($_POST['account_number']??''),trim($_POST['imei']??''),trim($_POST['eid']??''),trim($_POST['id_type']??''),encrypt_secret(trim($_POST['id_value']??''))]);$oid=(int)db()->lastInsertId();if(trim($_POST['referred_by']??'')!==''){create_referral_for_order($oid,trim($_POST['referred_by']),$u['name'],(int)$d['provider_id']);}audit((int)$u['id'],'submit_order','order',$oid,['public_id'=>$public]);redirect(url('?page=success&order='.urlencode($public)));}
 $sources=db()->query("SELECT * FROM sale_sources WHERE active=1 ORDER BY name")->fetchAll();layout_start('Apply');?><section class="card application-card"><span class="pill"><?=e($d['provider'])?> · <?=e($d['category'])?></span><h1><?=e($d['name'])?></h1><div class="price">$<?=number_format((float)$d['monthly_price'],2)?>/mo</div><p class="muted">Submit your request securely. We manually review and process the provider order.</p><form method="post"><input type="hidden" name="_token" value="<?=e(csrf())?>"><div class="grid"><label>Email<input type="email" name="email" value="<?=e($u['email'])?>" required></label><label>Phone<input name="phone" value="<?=e($u['phone'])?>" required></label></div><label>How did you hear about this offer?<select name="source_id"><option value="">Select</option><?php foreach($sources as $x):?><option value="<?=$x['id']?>"><?=e($x['name'])?></option><?php endforeach;?></select></label><label>Referred by (if applicable)<input name="referred_by"></label><?php if(strtolower($d['category'])==='mobility'):?><label>Identity option<select name="id_type" required><option>Driver's Licence</option><option>Provider-approved alternative</option></select></label><label>Identity value<input name="id_value" autocomplete="off" required></label><label><input type="checkbox" name="porting" value="1"> I am porting my current number</label><div class="grid"><label>Current phone number<input name="current_phone"></label><label>Current provider<input name="current_provider"></label><label>Current provider account number<input name="account_number"></label></div><h3>For eSIM</h3><div class="grid"><label>IMEI<input name="imei"></label><label>EID<input name="eid"></label></div><?php else:?><label>Full service address<input name="address" required placeholder="Street, unit, city, province, postal code"></label><label>Basement / suite details<textarea name="basement" placeholder="If basement, mention basement/unit and entrance details."></textarea></label><label>Accepted ID type<select name="id_type" required><option>Driver's Licence</option><option>Provincial ID</option><option>Other provider-approved ID</option></select></label><label>ID value<input name="id_value" autocomplete="off" required></label><?php endif;?><div class="alert">By submitting, you are requesting manual order processing. Provider eligibility, final pricing and appointment availability remain subject to confirmation.</div><button>Submit order request</button></form></section><?php layout_end();exit;
}
if($page==='success'){require_login();layout_start('Submitted');?><section class="card narrow"><span class="pill">REQUEST RECEIVED</span><h1>You're all set.</h1><p>Order request <strong><?=e($_GET['order']??'')?></strong> has been submitted.</p><div class="alert success"><strong>We'll contact you within 1 hour during business hours</strong> to review your request, process the order and confirm your appointment date and time.</div><a class="button" href="<?=e(url('?page=orders'))?>">Track my request</a></section><?php layout_end();exit;}
if($page==='orders'){ $u=require_login();$s=db()->prepare("SELECT o.*,d.name deal,p.name provider FROM orders o JOIN deals d ON d.id=o.deal_id JOIN providers p ON p.id=o.provider_id WHERE o.user_id=? ORDER BY o.id DESC");$s->execute([$u['id']]);layout_start('My orders');?><section class="pagehead customer-head"><div><span class="login-kicker">YOUR SECURELINK</span><h1>My orders</h1><p class="muted">Track every request from submission to activation.</p></div></section><div class="grid order-grid"><?php foreach($s as $o):?><article class="card"><span class="pill"><?=e(strtoupper($o['status']))?></span><h2><?=e($o['provider'])?> · <?=e($o['deal'])?></h2><p><strong><?=e($o['public_id'])?></strong></p><?php if($o['appointment_at']):?><p>Appointment: <?=e($o['appointment_at'])?></p><?php endif;?><p class="muted">Submitted <?=e($o['created_at'])?></p><?php foreach(customer_updates((int)$o['id']) as $cu):?><div class="alert"><strong><?=e($cu['subject']?:'Update')?></strong><br><?=nl2br(e($cu['message']))?><br><small><?=e($cu['created_at'])?></small></div><?php endforeach;?></article><?php endforeach;?></div><?php layout_end();exit;}

if($page==='admin'){ require dirname(__DIR__).'/app/admin.php'; exit; }
if($page==='export'){ $a=require_admin();$type=$_GET['type']??'';$maps=['leads'=>"SELECT id,name,email,phone,stage,sales_agent,next_follow_up_at,lost_reason,created_at FROM leads",'orders'=>"SELECT public_id,category,status,contact_email,contact_phone,referred_by,sales_agent,provider_reference,appointment_at,lost_reason,created_at FROM orders",'referrals'=>"SELECT referred_by,referred_customer,reward_amount,status,eligible_at,paid_at,payment_reference,created_at FROM referrals"];
 if(!isset($maps[$type])){http_response_code(400);exit('Invalid export');}$rows=db()->query($maps[$type])->fetchAll();header('Content-Type: text/csv');header('Content-Disposition: attachment; filename="'.$type.'-'.date('Y-m-d').'.csv"');$out=fopen('php://output','w');if($rows){fputcsv($out,array_keys($rows[0]));foreach($rows as $r)fputcsv($out,$r);}fclose($out);exit;}
layout_start('Private telecom offers');?><section class="mock-hero"><div class="mock-copy"><span class="login-kicker">FAST • RELIABLE • SIMPLE</span><h1>Connections,<br><em>without the noise.</em></h1><p>A private telecom network built around clarity. Compare curated Internet and Mobility offers, request the right connection and let a real person handle the rest.</p><div class="mock-actions"><a class="button primary-glow" href="<?=e(url('?page=register'))?>">Explore private access <span>↗</span></a><a class="text-link" href="<?=e(url('?page=login'))?>">Already a member? Sign in →</a></div><div class="mock-proof"><span><b>01</b> DISCOVER</span><i></i><span><b>02</b> REQUEST</span><i></i><span><b>03</b> ACTIVATE</span></div></div><div class="signal-world" aria-hidden="true"><div class="signal-halo h1"></div><div class="signal-halo h2"></div><div class="signal-halo h3"></div><div class="signal-house"><span></span><b></b></div><div class="signal-wave w1"></div><div class="signal-wave w2"></div><div class="signal-wave w3"></div><div class="signal-node n1"></div><div class="signal-node n2"></div><div class="signal-node n3"></div></div></section><section class="experience-strip"><span>PRIVATE TELECOM NETWORK</span><h2>One portal. Every connection.</h2><p>Private pricing, guided ordering and human support — without the usual telecom maze.</p><div class="experience-grid"><article><div class="feature-orb fibre">⌁</div><small>01 / HOME</small><h3>Fibre that<br>feels instant.</h3><p>Curated home Internet offers with clear monthly pricing and terms.</p></article><article><div class="feature-orb mobile">◔</div><small>02 / MOBILE</small><h3>Plans built<br>around you.</h3><p>Mobility offers selected for value, coverage and how you actually use data.</p></article><article><div class="feature-orb human">✦</div><small>03 / HUMAN</small><h3>Real support.<br>Zero maze.</h3><p>Submit your request online. We review, process and guide activation personally.</p></article></div></section><section class="mock-cta"><div><span class="login-kicker">YOUR PRIVATE CONNECTION DESK</span><h2>Ready when<br><em>you are.</em></h2></div><div><p>Request access once. After approval, private offers and order tracking live in one secure place.</p><a class="button primary-glow" href="<?=e(url('?page=register'))?>">Request access <span>↗</span></a></div></section><?php layout_end();
