<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/bootstrap.php';
require_once dirname(__DIR__).'/app/operations.php';
$page=$_GET['page']??'home';
if($page==='install'){ require dirname(__DIR__).'/app/install.php'; exit; }
if(!empty($_GET['campaign'])){ $_SESSION['campaign_code']=preg_replace('/[^A-Za-z0-9_-]/','',$_GET['campaign']); }
function layout_start(string $title): void { $u=user(); ?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/assets/app.css"><title><?=e($title)?> · <?=e(envv('APP_NAME','Telecom Portal'))?></title></head><body><main class="shell"><nav class="nav"><a class="brand" href="/"><?=e(envv('APP_NAME','Telecom Portal'))?></a><div class="links"><?php if($u): ?><a href="/?page=deals">Deals</a><a href="/?page=orders">My Orders</a><?php if(in_array($u['role'],['owner','admin'],true)): ?><a href="/?page=admin">Admin</a><?php endif; ?><a href="/?page=logout">Logout</a><?php else: ?><a href="/?page=login">Sign in</a><a href="/?page=register">Request access</a><?php endif; ?></div></nav><?php }
function layout_end(): void { echo '</main></body></html>'; }
if($page==='logout'){ session_destroy(); redirect('/'); }

if($page==='register'){
 if($_SERVER['REQUEST_METHOD']==='POST'){ csrf_check(); $n=trim($_POST['name']??'');$em=strtolower(trim($_POST['email']??''));$ph=trim($_POST['phone']??'');$pw=$_POST['password']??''; if(!$n||!filter_var($em,FILTER_VALIDATE_EMAIL)||strlen($pw)<10) exit('Check your details.'); try{$s=db()->prepare("INSERT INTO users(name,email,phone,password_hash) VALUES(?,?,?,?)");$s->execute([$n,$em,$ph,password_hash($pw,PASSWORD_DEFAULT)]);redirect('/?page=login&registered=1');}catch(Throwable $e){exit('Account could not be created. Email may already exist.');}}
 layout_start('Request access'); ?><section class="card narrow"><h1>Request access</h1><p class="muted">Create your private account. Deals become visible after approval.</p><form method="post"><input type="hidden" name="_token" value="<?=e(csrf())?>"><label>Full name<input name="name" required></label><label>Email<input type="email" name="email" required></label><label>Phone<input name="phone" required></label><label>Password<input type="password" name="password" minlength="10" required></label><button>Create account</button></form></section><?php layout_end();exit;
}
if($page==='login'){
 if($_SERVER['REQUEST_METHOD']==='POST'){csrf_check();$s=db()->prepare('SELECT * FROM users WHERE email=?');$s->execute([strtolower(trim($_POST['email']??''))]);$u=$s->fetch();if($u&&password_verify($_POST['password']??'',$u['password_hash'])){session_regenerate_id(true);$_SESSION['uid']=$u['id'];audit((int)$u['id'],'login');redirect($u['role']==='customer'?'/?page=deals':'/?page=admin');} $err='Invalid email or password.';}
 layout_start('Sign in');?><section class="card narrow"><h1>Welcome back</h1><?php if(!empty($_GET['registered'])):?><p class="alert success">Account created. An administrator must approve access.</p><?php endif;if(isset($err)):?><p class="alert"><?=e($err)?></p><?php endif;?><form method="post"><input type="hidden" name="_token" value="<?=e(csrf())?>"><label>Email<input type="email" name="email" required></label><label>Password<input type="password" name="password" required></label><button>Sign in</button></form></section><?php layout_end();exit;
}
if($page==='pending'){ $u=require_login(); layout_start('Pending approval');?><section class="card narrow"><span class="pill">PENDING APPROVAL</span><h1>We're reviewing your access.</h1><p class="muted">Your account must be approved before private pricing and offers become available.</p></section><?php layout_end();exit; }

if($page==='deals'){
 $u=require_approved(); $q=db()->query("SELECT d.*,p.name provider FROM deals d JOIN providers p ON p.id=d.provider_id WHERE d.status='active' AND p.status='active' AND (d.starts_at IS NULL OR d.starts_at<=datetime('now')) AND (d.expires_at IS NULL OR d.expires_at>=datetime('now')) ORDER BY p.display_order,d.id DESC"); $deals=$q->fetchAll();
 layout_start('Deals');?><div class="hero"><span class="pill">PRIVATE OFFERS</span><h1>Find the right connection.</h1><p class="muted">Compare active Internet and Mobility offers available through your approved account.</p></div><div class="grid"><?php foreach($deals as $d):?><article class="card"><span class="pill"><?=e($d['provider'])?> · <?=e($d['category'])?></span><h2><?=e($d['name'])?></h2><p class="muted"><?=e($d['description'])?></p><div class="price">$<?=number_format((float)$d['monthly_price'],2)?><small>/mo</small></div><p><?=e($d['speed_data'])?></p><?php $rw=(float)$d['bill_credit']+(float)$d['referral_reward']+(float)$d['other_reward'];if($rw>0):?><div class="reward"><strong>$<?=number_format($rw,0)?> potential rewards</strong><br><small>See terms and eligibility.</small></div><?php endif;?><a class="button" href="/?page=apply&id=<?=$d['id']?>">Get this deal</a></article><?php endforeach;if(!$deals):?><section class="card"><h2>No active deals</h2><p class="muted">New offers will appear here when published.</p></section><?php endif;?></div><?php layout_end();exit;
}
if($page==='apply'){
 $u=require_approved();$id=(int)($_GET['id']??0);$s=db()->prepare("SELECT d.*,p.name provider,p.id provider_id FROM deals d JOIN providers p ON p.id=d.provider_id WHERE d.id=? AND d.status='active' AND p.status='active'");$s->execute([$id]);$d=$s->fetch();if(!$d){http_response_code(404);exit('Deal unavailable.');}
 if($_SERVER['REQUEST_METHOD']==='POST'){csrf_check();$public='SL-'.date('ymd').'-'.strtoupper(bin2hex(random_bytes(3)));$source=(int)($_POST['source_id']??0)?:null;$port=!empty($_POST['porting'])?1:0;$snapshot=json_encode($d,JSON_UNESCAPED_SLASHES);$sql="INSERT INTO orders(public_id,user_id,deal_id,provider_id,category,deal_snapshot,source_id,referred_by,contact_email,contact_phone,service_address,basement_details,porting,current_phone,current_provider,current_account_number,imei,eid,id_type,id_value_encrypted) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";$st=db()->prepare($sql);$st->execute([$public,$u['id'],$d['id'],$d['provider_id'],$d['category'],$snapshot,$source,trim($_POST['referred_by']??''),trim($_POST['email']??$u['email']),trim($_POST['phone']??$u['phone']),trim($_POST['address']??''),trim($_POST['basement']??''),$port,trim($_POST['current_phone']??''),trim($_POST['current_provider']??''),trim($_POST['account_number']??''),trim($_POST['imei']??''),trim($_POST['eid']??''),trim($_POST['id_type']??''),encrypt_secret(trim($_POST['id_value']??''))]);$oid=(int)db()->lastInsertId();if(trim($_POST['referred_by']??'')!==''){$r=db()->prepare("INSERT INTO referrals(order_id,referred_by,referred_customer,reward_amount) VALUES(?,?,?,?)");$r->execute([$oid,trim($_POST['referred_by']),$u['name'],(float)$d['referral_reward']]);}audit((int)$u['id'],'submit_order','order',$oid,['public_id'=>$public]);redirect('/?page=success&order='.urlencode($public));}
 $sources=db()->query("SELECT * FROM sale_sources WHERE active=1 ORDER BY name")->fetchAll();layout_start('Apply');?><section class="card"><span class="pill"><?=e($d['provider'])?> · <?=e($d['category'])?></span><h1><?=e($d['name'])?></h1><div class="price">$<?=number_format((float)$d['monthly_price'],2)?>/mo</div><p class="muted">Submit your request securely. We manually review and process the provider order.</p><form method="post"><input type="hidden" name="_token" value="<?=e(csrf())?>"><div class="grid"><label>Email<input type="email" name="email" value="<?=e($u['email'])?>" required></label><label>Phone<input name="phone" value="<?=e($u['phone'])?>" required></label></div><label>How did you hear about this offer?<select name="source_id"><option value="">Select</option><?php foreach($sources as $x):?><option value="<?=$x['id']?>"><?=e($x['name'])?></option><?php endforeach;?></select></label><label>Referred by (if applicable)<input name="referred_by"></label><?php if(strtolower($d['category'])==='mobility'):?><label>Identity option<select name="id_type" required><option>Driver's Licence</option><option>Provider-approved alternative</option></select></label><label>Identity value<input name="id_value" autocomplete="off" required></label><label><input type="checkbox" name="porting" value="1"> I am porting my current number</label><div class="grid"><label>Current phone number<input name="current_phone"></label><label>Current provider<input name="current_provider"></label><label>Current provider account number<input name="account_number"></label></div><h3>For eSIM</h3><div class="grid"><label>IMEI<input name="imei"></label><label>EID<input name="eid"></label></div><?php else:?><label>Full service address<input name="address" required placeholder="Street, unit, city, province, postal code"></label><label>Basement / suite details<textarea name="basement" placeholder="If basement, mention basement/unit and entrance details."></textarea></label><label>Accepted ID type<select name="id_type" required><option>Driver's Licence</option><option>Provincial ID</option><option>Other provider-approved ID</option></select></label><label>ID value<input name="id_value" autocomplete="off" required></label><?php endif;?><div class="alert">By submitting, you are requesting manual order processing. Provider eligibility, final pricing and appointment availability remain subject to confirmation.</div><button>Submit order request</button></form></section><?php layout_end();exit;
}
if($page==='success'){require_login();layout_start('Submitted');?><section class="card narrow"><span class="pill">REQUEST RECEIVED</span><h1>You're all set.</h1><p>Order request <strong><?=e($_GET['order']??'')?></strong> has been submitted.</p><div class="alert success"><strong>We'll contact you within 1 hour during business hours</strong> to review your request, process the order and confirm your appointment date and time.</div><a class="button" href="/?page=orders">Track my request</a></section><?php layout_end();exit;}
if($page==='orders'){ $u=require_login();$s=db()->prepare("SELECT o.*,d.name deal,p.name provider FROM orders o JOIN deals d ON d.id=o.deal_id JOIN providers p ON p.id=o.provider_id WHERE o.user_id=? ORDER BY o.id DESC");$s->execute([$u['id']]);layout_start('My orders');?><h1>My orders</h1><div class="grid"><?php foreach($s as $o):?><article class="card"><span class="pill"><?=e(strtoupper($o['status']))?></span><h2><?=e($o['provider'])?> · <?=e($o['deal'])?></h2><p><strong><?=e($o['public_id'])?></strong></p><?php if($o['appointment_at']):?><p>Appointment: <?=e($o['appointment_at'])?></p><?php endif;?><p class="muted">Submitted <?=e($o['created_at'])?></p></article><?php endforeach;?></div><?php layout_end();exit;}

if($page==='admin'){ require dirname(__DIR__).'/app/admin.php'; exit; }
if($page==='export'){ $a=require_admin();$type=$_GET['type']??'';$maps=['leads'=>"SELECT id,name,email,phone,stage,sales_agent,next_follow_up_at,lost_reason,created_at FROM leads",'orders'=>"SELECT public_id,category,status,contact_email,contact_phone,referred_by,sales_agent,provider_reference,appointment_at,lost_reason,created_at FROM orders",'referrals'=>"SELECT referred_by,referred_customer,reward_amount,status,eligible_at,paid_at,payment_reference,created_at FROM referrals"];
 if(!isset($maps[$type])){http_response_code(400);exit('Invalid export');}$rows=db()->query($maps[$type])->fetchAll();header('Content-Type: text/csv');header('Content-Disposition: attachment; filename="'.$type.'-'.date('Y-m-d').'.csv"');$out=fopen('php://output','w');if($rows){fputcsv($out,array_keys($rows[0]));foreach($rows as $r)fputcsv($out,$r);}fclose($out);exit;}
layout_start('Private telecom offers');?><section class="hero"><span class="pill">PRIVATE · APPROVAL REQUIRED</span><h1>Compare telecom offers without the noise.</h1><p class="muted">A private portal for approved customers to review Internet and Mobility offers, submit an order request and track confirmation.</p><div class="row"><a class="button" href="/?page=register">Request access</a><a class="button secondary" href="/?page=login">Sign in</a></div></section><div class="grid"><section class="card"><h2>Compare clearly</h2><p class="muted">Monthly pricing, rewards and important terms in one clean view.</p></section><section class="card"><h2>Private access</h2><p class="muted">Pricing remains behind account approval.</p></section><section class="card"><h2>Human processing</h2><p class="muted">Submit online; your order is reviewed and processed manually.</p></section></div><?php layout_end();
